categories:
  - "Automotive/Storage/Roof Trays/Alpha Platform"
  - "Automotive/Storage/Roof Trays/Beta Platform"
  - "Automotive/Storage/Roof Trays/Platform Accessories"
  - "Automotive/Storage/Roof Trays/Roof Top Tents"
  - "Automotive/Storage/Roof Trays/Luggage Bags"
  - "Automotive/Storage/Roof Trays/Roof Baskets"
  - "Automotive/Storage/Roof Trays/Roof Boxes"
  - "Automotive/Storage/Roof Trays/Complete Kits"
  - "Automotive/Storage/Roof Racks/Cross Bar Roof Racks"
  - "Automotive/Storage/Roof Racks/Canopy Roof Systems"
  - "Automotive/Storage/Roof Racks/Load Securing"
  - "Automotive/Storage/Ute Tub Racks/Sigma-Deck"
  - "Automotive/Storage/Ute Tub Racks/Sigma-Deck Accessories"
  - "Automotive/Storage/Sport & Awnings/Awnings"
  - "Automotive/Storage/Sport & Awnings/Bike Carriers"
  - "Automotive/Storage/Sport & Awnings/Water Sports"
  - "Automotive/Storage/Sport & Awnings/Snow Sports"
  - "Automotive/Storage/Work Solutions/Conduit & Carriers"
  - "Automotive/Storage/Work Solutions/Complete Ladder Carriers"
  - "Automotive/Storage/Work Solutions/Ladder Carrier Accessories"
  - "Automotive/Storage/Work Solutions/Ladder Rack Rails"
  - "Automotive/Storage/Work Solutions/Ladder & Roof Rack Rollers"
  - "Automotive/Storage/Spares, Brackets & Components/Brackets"
  - "Automotive/Storage/Spares, Brackets & Components/Fitting Kits"
  - "Automotive/Storage/Spares, Brackets & Components/Spare Parts"
  - "Automotive/Storage/Spares, Brackets & Components/Roof Rack Parts"

brands:
  - "LoadMaster"
  - "RackTec"
  - "CargoForce"
  - "SkyMount"
  - "TerraRack" 